kind: Template
apiVersion: v1
metadata:
  name: hello-template
objects:

- kind: ImageStream
  apiVersion: v1
  metadata:
    annotations:
    labels:
      app: hello
    name: hello
  spec:
  lookupPolicy:
    local: false

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: hello 
    labels:
      app: hello
  spec:
    runPolicy: Serial 
    triggers: 
      -
        type: GitHub
        github:
          secret: secret101
      -
        type: ImageChange
    source: 
      git:
        uri: "https://github.com/drnic/php-helloworld.git"
    strategy: 
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "php:latest"
          namespace: openshift    
    output: 
      to:
        kind: ImageStreamTag
        name: "hello:latest"

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: hello
    labels:
      app: hello
  spec:
    template: 
      metadata:
        labels:
          name: hello
          app: hello
      spec:
        containers:
          - name: hello
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: TCP
        restartPolicy: Always
    replicas: 1 
    triggers:
      - type: ConfigChange
      - type: ImageChange 
        imageChangeParams:
          automatic: true
          containerNames:
            - hello
          from:
            kind: ImageStreamTag
            name: "hello:latest"
    strategy: 
        type: Rolling
    paused: false 
    revisionHistoryLimit: 2 
    minReadySeconds: 0 

- kind: Service
  apiVersion: v1
  metadata:
    annotations:
    name: hello
    labels:
      app: hello
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: hello
    type: ClusterIP
    sessionAffinity: None

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: hello
    labels:
      app: hello
  annotations:
  spec:
    to:
      kind: Service
      name: hello
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None  