kind: Template
apiVersion: v1
metadata:
  name: webappcore-docker-template
objects:

- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: webappcore-docker
    name: webappcore-docker
  spec:
    lookupPolicy:
      local: false

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: webappcore-docker 
    labels:
      app: webappcore-docker
  spec:
    runPolicy: Serial 
    triggers: 
      -
        type: GitHub
        github:
          secret: "secret101"

      - type: Generic
        generic:
          secret: "secret101"
    source: 
      git:
        uri: "https://github.com/mchudinov/WebAppTestNetCore31.git"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: /WebApplication1/Dockerfile    
    output: 
      to:
        kind: ImageStreamTag
        name: "webappcore-docker:latest"

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: webappcore-docker
    labels:
      app: webappcore-docker
  spec:
    template: 
      metadata:
        labels:
          name: webappcore-docker
          app: webappcore-docker
      spec:
        containers:
          - name: webappcore-docker
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: RUN_ENV
                value: OpenShift-With-Dockerfile 
        restartPolicy: Always
    replicas: 1 
    triggers:
      - type: ConfigChange 
      - type: ImageChange 
        imageChangeParams:
          automatic: true
          containerNames:
            - "webappcore-docker"
          from:
            kind: ImageStreamTag
            name: "webappcore-docker:latest"
    strategy: 
      type: Rolling
    paused: false 
    revisionHistoryLimit: 5
    minReadySeconds: 0 

- kind: Service
  apiVersion: v1
  metadata:
    name: webappcore-docker
    labels:
      app: webappcore-docker
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: webappcore-docker
    type: ClusterIP
    sessionAffinity: None

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: webappcore-docker
    labels:
      app: webappcore-docker
  spec:
    to:
      kind: Service
      name: webappcore-docker
      weight: 100
    port:
      targetPort: 8080-tcp
  wildcardPolicy: None  